# build stage
FROM golang:1.24.2-alpine3.21 

WORKDIR /amdp-task

COPY go.mod go.sum ./

COPY internal/ ./internal/

COPY cmd/ ./cmd/

ENV GOPROXY=https://goproxy.io,direct

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd

RUN go install github.com/go-delve/delve/cmd/dlv@latest

EXPOSE 4000

CMD [ "dlv",  "--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/amdp-task/app" ]
