// Code generated by "stringer -type=LevelFilter -output=cfg_lvlf_string.go"; DO NOT EDIT.

package logging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Gte-0]
	_ = x[Gt-1]
	_ = x[NotEq-2]
	_ = x[Eq-3]
	_ = x[Lt-4]
	_ = x[Lte-5]
}

const _LevelFilter_name = "GteGtNotEqEqLtLte"

var _LevelFilter_index = [...]uint8{0, 3, 5, 10, 12, 14, 17}

func (i LevelFilter) String() string {
	if i >= LevelFilter(len(_LevelFilter_index)-1) {
		return "LevelFilter(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LevelFilter_name[_LevelFilter_index[i]:_LevelFilter_index[i+1]]
}
