// Code generated by "stringer -type=EncoderType -output=cfg_enc_string.go"; DO NOT EDIT.

package logging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Console-0]
	_ = x[JSON-1]
}

const _EncoderType_name = "ConsoleJSON"

var _EncoderType_index = [...]uint8{0, 7, 11}

func (i EncoderType) String() string {
	if i >= EncoderType(len(_EncoderType_index)-1) {
		return "EncoderType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EncoderType_name[_EncoderType_index[i]:_EncoderType_index[i+1]]
}
