// Code generated by "stringer -type=Environment -output=cfg_env_string.go"; DO NOT EDIT.

package logging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Development-0]
	_ = x[Production-1]
}

const _Environment_name = "DevelopmentProduction"

var _Environment_index = [...]uint8{0, 11, 21}

func (i Environment) String() string {
	if i >= Environment(len(_Environment_index)-1) {
		return "Environment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Environment_name[_Environment_index[i]:_Environment_index[i+1]]
}
