// Code generated by "stringer -type=MessageType -output=msg_type_string.go"; DO NOT EDIT.

package messaging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Event-0]
	_ = x[Command-1]
	_ = x[Query-2]
}

const _MessageType_name = "EventCommandQuery"

var _MessageType_index = [...]uint8{0, 5, 12, 17}

func (i MessageType) String() string {
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
