// Code generated by "stringer -type=ObjectState -output=obj_state_string.go"; DO NOT EDIT.

package entities

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Initial-0]
	_ = x[Complete-1]
}

const _ObjectState_name = "IncompleteComplete"

var _ObjectState_index = [...]uint8{0, 10, 18}

func (i ObjectState) String() string {
	if i >= ObjectState(len(_ObjectState_index)-1) {
		return "ObjectState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectState_name[_ObjectState_index[i]:_ObjectState_index[i+1]]
}
